# Generated by Django 6.0.2 on 2026-04-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0002_studysession_ended_at_studysession_host_peer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='active_peer_ids',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
